GET {{host}}/forms/batch/1
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

###

GET {{host}}/forms/batch/2
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

###