PUT {{host}}/data/batch/1
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "options": {
    "format": [
      "csv"
    ]
  }
}

###

PUT {{host}}/data/batch/1
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "options": {
    "format": [
      "csv2"
    ]
  }
}

###

PUT {{host}}/data/batch/2
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "options": {
    "format": [
      "csv2"
    ]
  }
}

###