PUT http://{{host}}/data/options/1
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "options": {
    "format": [
      "csv"
    ]
  }
}

###

PUT http://{{host}}/data/options/1
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "options": {
    "format": [
      "csv2"
    ]
  }
}

###

PUT http://{{host}}/data/options/2
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "options": {
    "format": [
      "csv2"
    ]
  }
}

###