GET {{host}}/data/settings
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

###

PUT {{host}}/data/settings
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "main": {
    "headers": true,
    "fields": [
      "id",
      "createdAt",
      "updatedAt",
      "data.addressFields.[field.name=address_1].value.city",
      "cart.total"
    ],
    "format": [
      "xlsx"
    ]
  }
}

###

PUT {{host}}/data/settings
Content-Type: application/json
Accept-Language: ru_RU
X-PLUGIN-TOKEN: {{token}}

{
  "main": {
    "headers": false,
    "fields": [
      "id",
      "qwerty",
      "createdAt",
      "updatedAt",
      "cart.totalPrice"
    ],
    "format": [
      "xlsx", "xls"
    ]
  }
}

###